FROM distcc/base

LABEL maintainer=""

RUN apt-get update && \
    apt-get install -y clang-3.8 build-essential && \
    apt-get remove gcc g++ && \
    rm -rf /var/lib/apt/lists/* && \
    update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.8 50 && \
    update-alternatives --install /usr/bin/cc cc /usr/bin/clang-3.8 50
