name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ubuntu:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        cc: [gcc, clang]
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev libiberty-dev libavahi-client-dev
    - name: Configure
      run: ./autogen.sh && ./configure
    - name: make
      run: make -j$(nproc)
    - name: make check
      run: make check

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: brew install automake
    - name: Configure
      run: ./autogen.sh && ./configure --without-libiberty
    - name: make
      run: make -j$(nproc)
    - name: make check
      run: make check
